<?php

namespace DepotBundle\Repository;

use DepotBundle\Entity\Devoir;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommentaireParentNotNull(Devoir $devoir)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.commentaire_parent is not null AND c.devoir = :devoir')
        ->setParameter('devoir', $devoir);

        return $qb->getQuery()
            ->getResult();
    }
}
