<?php

namespace DepotBundle\Repository;

/**
 * FillExtensionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileExtensionRepository extends \Doctrine\ORM\EntityRepository
{
}
