<?php

namespace DepotBundle\Repository;

/**
 * Groupe_projetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Groupe_projetRepository extends \Doctrine\ORM\EntityRepository
{
}
