<?php

namespace DepotBundle\Repository;

/**
 * RenduRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RenduRepository extends \Doctrine\ORM\EntityRepository
{
}
