<?php

namespace DepotBundle\Repository;
use DepotBundle\Entity\Devoir;
use UserBundle\Entity\User;

/**
 * Groupe_projetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGroupeProjetRepository extends \Doctrine\ORM\EntityRepository
{

}
