users_admin:
    path:     /
    defaults: { _controller: DepotBundle:Admin\UserAdmin:index }

users_admin_edit:
    path:      /users/edit/{id}
    defaults: { _controller: DepotBundle:Admin\UserAdmin:edit }

users_admin_delete:
    path:      /users/delete/{id}
    defaults: { _controller: DepotBundle:Admin\UserAdmin:delete }

users_admin_validate_account:
    path:      /users/validate_account/{id}
    defaults: { _controller: DepotBundle:Admin\UserAdmin:validateAccount }

users_admin_disable_account:
    path:      /users/disable_account/{id}
    defaults: { _controller: DepotBundle:Admin\UserAdmin:disableAccount }

users_admin_new:
    path:      /users/new
    defaults: { _controller: DepotBundle:Admin\UserAdmin:new }


ue_list:
    path:   /ues
    defaults: { _controller: DepotBundle:Admin\UE:list }

ue_add:
    path:   /ues/new
    defaults: { _controller: DepotBundle:Admin\UE:add }

ue_delete:
    path:   /ues/delete/{id}
    defaults: { _controller: DepotBundle:Admin\UE:delete }

ue_edit:
    path:   /ues/edit/{id}
    defaults: { _controller: DepotBundle:Admin\UE:edit }

import_admin:
    path: /import
    defaults: { _controller: DepotBundle:Admin\Import:import }

groupe_add:
    path: /groupes/add/{ue}
    defaults: { _controller: DepotBundle:Admin\Groupe:add }

groupe_edit:
    path:   /groupes/edit/{id}
    defaults: { _controller: DepotBundle:Admin\Groupe:edit }

groupe_delete:
    path:   /groupes/delete/{id}
    defaults: { _controller: DepotBundle:Admin\Groupe:delete }