services:
#    depot.example:
#        class: DepotBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    utility.grouperendu:
        class: DepotBundle\Utility\GroupeRenduUtility
