user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

depot:
    resource: "@DepotBundle/Resources/config/routing.yml"
    prefix:   /depot

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
