depot:
    resource: "@DepotBundle/Resources/config/routing.yml"
    prefix:   /depot

depot_admin:
    resource: "@DepotBundle/Resources/config/routing_admin.yml"
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: "/user/profil"

fos_user_resetting_request:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: "/user/compte"

fos_user_profile_show:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: "/user/profil"

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

mgilet_notifications:
    resource: "@DepotBundle/Controller/NotificationController.php"
    prefix: /notifications
    type: annotation

view_by_token:
    path: /devoir/view/{utoken}
    defaults: { _controller: DepotBundle:Devoir:viewbytoken }
    methods: GET


