depot:
    resource: "@DepotBundle/Resources/config/routing.yml"
    prefix:   /depot

depot_admin:
    resource: "@DepotBundle/Resources/config/routing_admin.yml"
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /