<?php

namespace UserBundle\Repository;
use UserBundle\Entity\User;
use UserBundle\UserBundle;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByRole($role)
    {
        $qb = $this->createQueryBuilder('u')
            ->where('u.roles LIKE :role')
            ->setParameter('role', "%$role%");
        
        return $qb->getQuery()->getResult();
    }
    
    public function findByGroupe($groupe)
    {
        $qb = $this->createQueryBuilder('u')
                ->innerJoin('u.groupes', 'g')
                ->where('g.id = :groupe')
                ->setParameter('groupe', $groupe);
        return $qb->getQuery()->getResult();
    }
    
    public function findIfUserAppartientGroupeUE($ue)
    {
        $qb = $this->createQueryBuilder('u')
                ->innerJoin('u.groupes', 'g')
                ->where('g.UE = :ue')
                ->setParameter('ue', $ue->getId())
                ->getQuery()->getResult();
        return $qb;
    }
}
