UserBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        first_name:
            type: string
            length: 60
            nullable: true

        last_name:
            type: string
            length: 60
            nullable: true

    oneToMany:
        commentaires:
            targetEntity: DepotBundle\Entity\Commentaire
            mappedBy: user

    lifecycleCallbacks: {  }
