app_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

user_profil:
    path:     /user/profil
    defaults: { _controller: UserBundle:UserProfile:index }

user_demandecompte:
    path:     /user/demandecompte
    defaults: { _controller: UserBundle:UserRegistration:demande }