DepotBundle\Entity\Commentaire:
    type: entity
    table: null
    repositoryClass: DepotBundle\Repository\CommentaireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        texte:
            type: string
            length: 60

        date:
            type: datetime

    manyToOne:
        user:
            targetEntity: UserBundle\Entity\User
            inversedBy: commentaires

        devoir:
            targetEntity: DepotBundle\Entity\Devoir
            inversedBy: commentaires

        commentaire_parent:
            targetEntity: DepotBundle\Entity\Commentaire
            inversedBy: commentaires_fils

    oneToMany:
        commentaires_fils:
            targetEntity: DepotBundle\Entity\Commentaire
            mappedBy: commentaire_parent

    lifecycleCallbacks: {  }
