DepotBundle\Entity\Devoir:
    type: entity
    table: null
    repositoryClass: DepotBundle\Repository\DevoirRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        intitule:
            type: text

        titre:
            type: string
            length: 60

        fichier:
            type: string
            length: 255
            nullable: true


    oneToMany:
        groupes_projets:
            targetEntity: Groupe_projet
            mappedBy: devoir

        groupe_devoir:
            targetEntity: Groupe_Devoir
            mappedBy: devoir

    manyToOne:
         UE:
             targetEntity: UE
             inversedBy: devoirs

    manyToMany:
        extensions:
            targetEntity: DepotBundle\Entity\FileExtension
            inversedBy: devoirs

    lifecycleCallbacks: {  }
