DepotBundle\Entity\Groupe_projet:
    type: entity
    table: null
    repositoryClass: DepotBundle\Repository\Groupe_projetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 60
        fichier:
            type: string
            length: 200
            nullable: true
        filename:
            type: string
            length: 200
            nullable: true
        token:
            type: string
            length: 200
            nullable: true

        date:
            type: datetime
            nullable: true

    oneToMany:
        users_groupes_projets:
            targetEntity: DepotBundle\Entity\UserGroupeProjet
            mappedBy: groupe_projet

    manyToOne:
        devoir:
            targetEntity: Devoir
            inversedBy: groupes_projets

        groupe:
            targetEntity: Groupe
            inversedBy: groupes_projets

        groupe_devoir:
            targetEntity: Groupe_devoir
            inversedBy: groupes_projets

    lifecycleCallbacks: {  }
