DepotBundle\Entity\Notification:
    type: entity
    table: null
    repositoryClass: DepotBundle\Repository\NotificationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        titre:
            type: string
            length: 60

        texte:
            type: string
            length: 60

        date:
            type: date

    manyToOne:
        user:
            targetEntity: UserBundle\Entity\User
            inversedBy: notifications

    lifecycleCallbacks: {  }
