DepotBundle\Entity\Rendu:
    type: entity
    table: null
    repositoryClass: DepotBundle\Repository\RenduRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        fichier:
            type: string
            length: 60

        date:
            type: date

    lifecycleCallbacks: {  }
