DepotBundle\Entity\UE:
    type: entity
    table: null
    repositoryClass: DepotBundle\Repository\UERepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        code:
            type: string
            length: 60

        nom:
            type: string
            length: 60

    oneToMany:
        devoirs:
            targetEntity: Devoir
            mappedBy: UE
        groupes:
            targetEntity: Groupe
            mappedBy: UE

    manyToMany:
        users:
            targetEntity: UserBundle\Entity\User
            mappedBy: ues



    lifecycleCallbacks: {  }
